### ISSUE TITLE
Statistics dashboard not showing SES opens but chart shows opens and clicks

### ISSUE THREAD

**Issue by dircm** [spatie/mailcoach-support#181] opened 2020-05-12 10:53 UTC
After campaign is sent, webhooks receive SES notifications and seem to process but dashboard statistics dont update.  

The opens and clicks DO show correct number in the line chart however (see image).

![Statistics updating](https://user-images.githubusercontent.com/18188561/81674661-e536d980-9490-11ea-9f65-3e48ec6ad178.jpg)

Horizon shows queues processing, no errors :

`Horizon started successfully.
[2020-05-12 09:53:35][36] Processing: Spatie\Mailcoach\Jobs\SendMailJob
[2020-05-12 09:53:35][36] Processed:  Spatie\Mailcoach\Jobs\SendMailJob
[2020-05-12 09:53:35][37] Processing: Spatie\Mailcoach\Jobs\SendMailJob
[2020-05-12 09:53:36][37] Processed:  Spatie\Mailcoach\Jobs\SendMailJob
[2020-05-12 09:53:38][38] Processing: Spatie\MailcoachSesFeedback\ProcessSesWebhookJob
[2020-05-12 09:53:38][38] Processed:  Spatie\MailcoachSesFeedback\ProcessSesWebhookJob
[2020-05-12 09:53:47][39] Processing: Spatie\MailcoachSesFeedback\ProcessSesWebhookJob
[2020-05-12 09:53:47][39] Processed:  Spatie\MailcoachSesFeedback\ProcessSesWebhookJob
[2020-05-12 09:53:47][40] Processing: Spatie\MailcoachSesFeedback\ProcessSesWebhookJob
[2020-05-12 09:53:47][40] Processed:  Spatie\MailcoachSesFeedback\ProcessSesWebhookJob
[2020-05-12 09:53:56][41] Processing: Spatie\MailcoachSesFeedback\ProcessSesWebhookJob
[2020-05-12 09:53:56][41] Processed:  Spatie\MailcoachSesFeedback\ProcessSesWebhookJob
[2020-05-12 09:54:44][42] Processing: Spatie\MailcoachSesFeedback\ProcessSesWebhookJob
[2020-05-12 09:54:45][42] Processed:  Spatie\MailcoachSesFeedback\ProcessSesWebhookJob
[2020-05-12 09:54:47][43] Processing: Spatie\Mailcoach\Jobs\CalculateStatisticsJob
[2020-05-12 09:54:47][43] Processed:  Spatie\Mailcoach\Jobs\CalculateStatisticsJob
[2020-05-12 09:55:18][44] Processing: Spatie\MailcoachSesFeedback\ProcessSesWebhookJob
[2020-05-12 09:55:18][44] Processed:  Spatie\MailcoachSesFeedback\ProcessSesWebhookJob
[2020-05-12 09:55:20][45] Processing: Spatie\Mailcoach\Jobs\CalculateStatisticsJob
[2020-05-12 09:55:20][45] Processed:  Spatie\Mailcoach\Jobs\CalculateStatisticsJob
[2020-05-12 09:58:06][46] Processing: Spatie\MailcoachSesFeedback\ProcessSesWebhookJob
[2020-05-12 09:58:06][46] Processed:  Spatie\MailcoachSesFeedback\ProcessSesWebhookJob
[2020-05-12 09:58:08][47] Processing: Spatie\Mailcoach\Jobs\CalculateStatisticsJob
[2020-05-12 09:58:08][47] Processed:  Spatie\Mailcoach\Jobs\CalculateStatisticsJob`

Laravel.log shows one error..

`[previous exception] [object] (PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'xxxx.mailcoach_campaign_opens.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by at /Users/tompw/Sites/xxxx/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:64)
[stacktrace]
#0 /Users/tompw/Sites/xxxx/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(64): PDO->prepare('select count(`s...', Array)
#1 /Users/tompw/Sites/xxxx/vendor/laravel/framework/src/Illuminate/Database/Connection.php(331): Doctrine\\DBAL\\Driver\\PDOConnection->prepare('select count(`s...')
#2 /Users/tompw/Sites/xxxx/vendor/laravel/framework/src/Illuminate/Database/Connection.php(664): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('select count(`s...', Array)
#3 /Users/tompw/Sites/xxxx/vendor/laravel/framework/src/Illuminate/Database/Connection.php(631): Illuminate\\Database\\Connection->runQueryCallback('select count(`s...', Array, Object(Closure))
#4 /Users/tompw/Sites/xxxx/vendor/laravel/framework/src/Illuminate/Database/Connection.php(339): Illuminate\\Database\\Connection->run('select count(`s...', Array, Object(Closure))
#5 /Users/tompw/Sites/xxxx/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2178): Illuminate\\Database\\Connection->select('select count(`s...', Array, true)
#6 /Users/tompw/Sites/xxxx/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2166): Illuminate\\Database\\Query\\Builder->runSelect()
#7 /Users/tompw/Sites/xxxx/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2661): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#8 /Users/tompw/Sites/xxxx/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2167): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))
#9 /Users/tompw/Sites/xxxx/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2269): Illuminate\\Database\\Query\\Builder->get()
#10 /Users/tompw/Sites/xxxx/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2236): Illuminate\\Database\\Query\\Builder->runPaginationCountQuery(Array)
#11 /Users/tompw/Sites/xxxx/vendor/spatie/laravel-mailcoach/src/Actions/Campaigns/CalculateStatisticsAction.php(74): Illuminate\\Database\\Query\\Builder->getCountForPagination(Array)
#12 /Users/tompw/Sites/xxxx/vendor/spatie/laravel-mailcoach/src/Actions/Campaigns/CalculateStatisticsAction.php(28): Spatie\\Mailcoach\\Actions\\Campaigns\\CalculateStatisticsAction->calculateOpenMetrics(Object(Spatie\\Mailcoach\\Models\\Campaign), 2)
#13 /Users/tompw/Sites/xxxx/vendor/spatie/laravel-mailcoach/src/Actions/Campaigns/CalculateStatisticsAction.php(15): Spatie\\Mailcoach\\Actions\\Campaigns\\CalculateStatisticsAction->calculateCampaignStatistics(Object(Spatie\\Mailcoach\\Models\\Campaign))
#14 /Users/tompw/Sites/xxxx/vendor/spatie/laravel-mailcoach/src/Jobs/CalculateStatisticsJob.php(39): Spatie\\Mailcoach\\Actions\\Campaigns\\CalculateStatisticsAction->execute(Object(Spatie\\Mailcoach\\Models\\Campaign))`

Thanks for the help !

**Comment by freekmurze** [comment] 2020-05-12 11:01
This is a duplicate of #176 

We'll fix it soon!

**Closed as completed by freekmurze** 2020-05-12 11:01 UTC
