### ISSUE TITLE
Incompatible php version for installing Mailcoach?

### ISSUE THREAD

**Issue by connecteev** [spatie/mailcoach-support#10] opened 2020-01-30 18:01 UTC
When I try to install Mailcoach using the docs, I get an error:
```
$ composer require "spatie/laravel-mailcoach:^1.0.0"                                                                
  [InvalidArgumentException]                                                                                            
  Package spatie/laravel-mailcoach at version ^1.0.0 has a PHP requirement incompatible with your PHP version (7.3.13)
```
                                                                
However the console shows my php version is 7.4.2. What gives?

```
$ php -v
PHP 7.4.2 (cli) (built: Jan 22 2020 06:30:58) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.2, Copyright (c), by Zend Technologies
```

**Comment by vesper8** [comment] 2020-01-30 19:50
it's possible your php-cli is different than php-fpm, what does phpinfo() say if you echo it from a laravel route?

**Comment by freekmurze** [comment] 2020-01-30 21:42
Like @vesper8, I also think this is a problem at your end. The error message says that you are running PHP 7.3.13. Please follow the advice given by @vesper8.

I'll close this for now, as I think this problem is unrelated to the package, but feel free to keep the conversation going.

**Closed as completed by freekmurze** 2020-01-30 21:42 UTC

**Comment by connecteev** [comment] 2020-02-01 05:43
@vesper8 @freekmurze I also think it's got to do with the php version, but I've still been unable to figure this out. Both the cli and phpinfo() in laravel are showing the exact same version (7.4.2)

$ php -v
PHP 7.4.2 (cli) (built: Jan 22 2020 06:30:58) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.2, Copyright (c), by Zend Technologies

But I still see this error on installation:
```
$ composer require "spatie/laravel-mailcoach:^1.0.0"

                                                                                                                        
  [InvalidArgumentException]                                                                                            
  Package spatie/laravel-mailcoach at version ^1.0.0 has a PHP requirement incompatible with your PHP version (7.3.13)  

```

**Comment by vesper8** [comment] 2020-02-01 11:02
Are you able to install the standalone version?

Can you also try installing the package version on a fresh installation of Laravel 6 to rule out a problem with your app's composer.json?

Could it be that you have this set in your composer.json?
```
  "config": {
    "platform": {
      "php": "7.3"
    }
  },

```

**Comment by connecteev** [comment] 2020-02-01 13:34
@vesper8 This is a brand new laravel app I installed using ```laravel new mailcoachapp```
I'm on this version:
```
$ php artisan --version
Laravel Framework 6.13.1
```
And I don't have this in my composer.json:
```
  "config": {
    "platform": {
      "php": "7.3"
    }
  },
```

I also tried the [standalone version](https://mailcoach.app/docs/app/installation/using-composer), it just gives me the same error:
```
$ composer create-project spatie/Mailcoach                                                                                                                         
  [InvalidArgumentException]                                                                                             
  Could not find package spatie/mailcoach with stability stable in a version installable using your PHP version 7.3.13. 
```

@freekmurze could this be a bug?

**Comment by vesper8** [comment] 2020-02-01 16:12
I think you might have two versions of php running

what does it say if you do `which php` in your cli?

and then whatever it returns, so for example if it returns `/usr/local/bin/php` then do a `/usr/local/bin/php -v`

You might also have one running at `/usr/bin/php`

What does this command return
`ps aux | grep php`

Any signs of 7.3 in there?

What about `ps aux | grep "php/7.3"`

Not sure how you installed php but on OSX at least I find it best to let Valet manage your php versions for you rather then using Homebrew. Try `valet use php@7.4`, you may need to uninstall php with `brew uninstall php` first

**Comment by freekmurze** [comment] 2020-02-01 17:04
@connecteev I can assure you that this is not a bug, but probably something going wrong at your end. Follow the suggestions made by @vesper8

**Comment by connecteev** [comment] 2020-02-01 20:33
@vesper8 @freekmurze thank you, thats quite astute of you to know this. It was exactly that, I had 2 versions of php...one in /usr/local/bin/php (which was the result of `which php`), and my .bash_profile had 
```
alias php='/usr/local/Cellar/php/7.4.2/bin/php'
```
I ended up doing:
```
cp /usr/local/Cellar/php/7.4.2/bin/php /usr/local/bin/php 
```
and after that the installation worked. Onward, now I can try the package, at least.

**Comment by freekmurze** [comment] 2020-02-01 20:50
Nice! Have fun discovering the package!

**Comment by connecteev** [comment] 2020-02-01 20:50
@freekmurze thank you sir!
