### ISSUE TITLE
Issue importing Subscribers on one-click installer

### ISSUE THREAD

**Issue by gathrlabs** [spatie/mailcoach-support#171] opened 2020-04-29 11:59 UTC
The import status seemed to stay stuck on "scheduled". SSHing into the droplet and running horizon seemed to fix this issue. Is it possible that Horizon wasn't started on install?

**Comment by riasvdv** [comment] 2020-04-30 12:06
Could you post the contents of the supervisor log? This should be starting horizon automatically

You can view the log by doing

`cat /var/log/supervisor/supervisord.log`

On your server through ssh

Maybe also the horizon log: `cat /var/www/html/horizon.log`

**Comment by gathrlabs** [comment] 2020-05-02 09:42
2020-04-25 11:54:15,634 CRIT Supervisor running as root (no user in config file)
2020-04-25 11:54:15,636 INFO Included extra file "/etc/supervisor/conf.d/horizon.conf" during parsing
2020-04-25 11:54:15,681 INFO RPC interface 'supervisor' initialized
2020-04-25 11:54:15,702 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2020-04-25 11:54:15,706 INFO supervisord started with pid 830
2020-04-25 11:54:16,709 INFO spawned: 'horizon' with pid 1026
2020-04-25 11:54:16,839 INFO exited: horizon (exit status 1; not expected)
2020-04-25 11:54:17,843 INFO spawned: 'horizon' with pid 1057
2020-04-25 11:54:17,972 INFO exited: horizon (exit status 1; not expected)
2020-04-25 11:54:19,976 INFO spawned: 'horizon' with pid 1355
2020-04-25 11:54:20,118 INFO exited: horizon (exit status 1; not expected)
2020-04-25 11:54:23,123 INFO spawned: 'horizon' with pid 1466
2020-04-25 11:54:23,211 INFO exited: horizon (exit status 1; not expected)
2020-04-25 11:54:24,215 INFO gave up: horizon entered FATAL state, too many start retries too quickly
2020-04-25 12:07:40,346 INFO spawned: 'horizon' with pid 12429
2020-04-25 12:07:41,639 INFO success: horizon entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

**Comment by gathrlabs** [comment] 2020-05-02 09:47
The only entry in the horizon log is 

`Horizon started successfully.`

**Comment by riasvdv** [comment] 2020-05-04 06:50
It seems like horizon failed to start the first few times, but then did successfully.

Is everything working for you currently? Seems like it was a once time mishap, haven't had any other reports and I can't reproduce it myself after starting a few one-click droplets.

Closing this for now

**Closed as completed by riasvdv** 2020-05-04 06:50 UTC
